# 09_verification.R — external benchmark and cross-source checks (build
# instruction §Verification), plus programmatic generation of NUMBERS.md.

source("scripts/00_common.R")

lines <- c("# Verification — BID2 motivation", "",
           paste("Generated by scripts/09_verification.R on", "2026-08-08"), "")

# ---- 1. GHED benchmark ---------------------------------------------------
ghed <- fread(file.path(DATA, "benchmark", "ghed_oop_mex.csv"))
fx   <- fread(file.path(DATA, "benchmark", "wb_fx_mxn.csv"))
defl <- inpc_deflators()

bench <- list()
for (y in ENIGH_YEARS) {
  con <- readRDS(file.path(DERIV, sprintf("enigh_hh_%d.rds", y)))
  d <- defl[yr == y, deflator]
  # back to nominal wave pesos, annualized (x4), per person
  tot_nom_annual <- con[, sum(salud / d * factor)] * 4
  pop <- con[, sum(tot_integ * factor)]
  enigh_pc_mxn <- tot_nom_annual / pop
  gy <- min(y, ghed[, max(year)])          # GHED currently ends 2023
  ghed_pc_mxn <- ghed[year == gy, ghed_oop_pc_usd] * fx[year == gy, fx_mxn_usd]
  bench[[as.character(y)]] <- data.table(
    year = y, enigh_oop_pc_mxn_nominal = round(enigh_pc_mxn),
    ghed_year = gy, ghed_oop_pc_mxn = round(ghed_pc_mxn),
    ratio_enigh_over_ghed = round(enigh_pc_mxn / ghed_pc_mxn, 3))
}
bench <- rbindlist(bench)
print(bench)
fwrite(bench, file.path(OUTTAB, "verification_ghed_benchmark.csv"))
lines <- c(lines, "## 1. ENIGH vs GHED out-of-pocket benchmark (nominal MXN per capita per year)", "",
           knitr_kable <- capture.output(print(bench)), "")

# ---- 2. ENIGH Tier 3 vs ENASEM overlap ratio -----------------------------
cmp <- fread(file.path(OUTTAB, "tier3_method_agreement_2024.csv"))
lines <- c(lines, "## 2-3. Tier 3 allocation methods, 2024 (quarterly pesos per person)",
           sprintf("Correlation across 18 age-sex cells: %.3f", cmp[, cor(reg, nta)]),
           capture.output(print(cmp[order(sex, age_grp)])), "")

# ---- 4. preventive shares: ENIGH vs ENSANUT ------------------------------
sens <- fread(file.path(OUTTAB, "fig7_ambiguous_sensitivity.csv"))
pcn <- fread(file.path(OUTTAB, "ensanut2024_preventive_share_by_nse.csv"))
lines <- c(lines, "## 4. Preventive share: ENIGH spending vs ENSANUT needs",
           "ENIGH preventive share of OOP spending (base / ambiguous->preventive):",
           capture.output(print(sens[, .(year, base = round(prev_share_base, 3),
                                         upper = round(prev_share_amb_to_prev, 3),
                                         ambiguous = round(amb_share, 3))])),
           "ENSANUT 2024 preventive share of last health need, by NSE tercile:",
           capture.output(print(pcn)), "")

# ---- 5. attrition summary ------------------------------------------------
a1 <- fread(file.path(OUTTAB, "enasem_attrition_by_frailty.csv"))
a2 <- fread(file.path(OUTTAB, "enasem_attrition_by_wealth.csv"))
lines <- c(lines, "## 5. ENASEM attrition 2018->2021 (non-death non-response)",
           capture.output(print(a1)), capture.output(print(a2)), "")

writeLines(lines, file.path(ROOT, "output", "VERIFICATION.md"))

# ---- NUMBERS.md ----------------------------------------------------------
figtabs <- list(
  "Figure 1 — Age-sex profile 2024 (both methods)" = "fig1_age_sex_profile_2024.csv",
  "Figure 2 — ENASEM observed profile 50+" = "fig2_enasem_observed_profile.csv",
  "Figure 3 — Profile by income tercile" = "fig3_profile_by_income_tercile.csv",
  "Figure 4 — Budget share by decile" = "fig4_budget_share_by_decile.csv",
  "Figure 5 — Zero spending by decile x 65+" = "fig5_zero_spending_by_decile_65plus.csv",
  "Figure 6 — Forgone care (ENSANUT)" = "fig6_forgone_care.csv",
  "Figure 6 — 2018 12-month cost battery" = "fig6_cost_battery_2018.csv",
  "Figure 7 — Composition by decile" = "fig7_composition_by_decile.csv",
  "Figure 7 — Ambiguous sensitivity" = "fig7_ambiguous_sensitivity.csv",
  "Figure 8 — Catastrophic incidence" = "fig8_catastrophic_by_decile.csv",
  "Figure 9 — Positive-spending distribution" = "fig9_positive_spending_distribution.csv",
  "Figure 10 — Spending response by wealth" = "fig10_spending_response_by_wealth.csv",
  "Figure 10 — Subsequent outcomes by wealth" = "fig10_subsequent_outcomes_by_wealth.csv",
  "Figure 11 — Wave stability" = "fig11_profile_stability.csv",
  "Frailty probit reproduction check" = "enasem_probit_reproduction_check.csv",
  "GHED benchmark" = "verification_ghed_benchmark.csv")

nl <- c("# NUMBERS — every figure's plotted values",
        "",
        "All monetary values: constant Aug–Nov 2024 pesos (general INPC) unless a",
        "table is explicitly nominal (GHED benchmark). All estimates design-based",
        "(strata × PSU × survey weights). ENIGH = INEGI; ENSANUT = INSP; ENASEM =",
        "INEGI open data. The draft must cite these tables, never values read off",
        "a figure. Machine-readable originals live beside this file in",
        "`output/tables/`.", "")
for (ttl in names(figtabs)) {
  f <- figtabs[[ttl]]
  dt <- fread(file.path(OUTTAB, f))
  num <- names(dt)[sapply(dt, is.numeric)]
  dt[, (num) := lapply(.SD, function(x) round(x, 4)), .SDcols = num]
  nl <- c(nl, paste0("## ", ttl), paste0("Source file: `output/tables/", f, "`"), "",
          "```", capture.output(print(dt, nrows = 200)), "```", "")
}
writeLines(nl, file.path(ROOT, "output", "NUMBERS.md"))
message("09_verification done")
