pearceip.law:
  surfaced: 5
  promoted: 0
  rejected: 0
  weight: 1.0
infectiousdiseaseadvisor.com:
  surfaced: 1
  promoted: 0
  rejected: 0
  weight: 1.0
cnbc.com:
  surfaced: 1
  promoted: 0
  rejected: 0
  weight: 1.0
fiercebiotech.com:
  surfaced: 4
  promoted: 0
  rejected: 0
  weight: 1.0
biospace.com:
  surfaced: 4
  promoted: 0
  rejected: 0
  weight: 1.0
finance.yahoo.com:
  surfaced: 1
  promoted: 0
  rejected: 0
  weight: 1.0
globenewswire.com:
  surfaced: 4
  promoted: 0
  rejected: 0
  weight: 1.0
ir.ionis.com:
  surfaced: 1
  promoted: 0
  rejected: 0
  weight: 1.0
hcplive.com:
  surfaced: 1
  promoted: 0
  rejected: 0
  weight: 1.0
deccanherald.com:
  surfaced: 1
  promoted: 0
  rejected: 0
  weight: 1.0
india-briefing.com:
  surfaced: 1
  promoted: 0
  rejected: 0
  weight: 1.0
cisema.com:
  surfaced: 1
  promoted: 0
  rejected: 0
  weight: 1.0
bloominglobal.com:
  surfaced: 1
  promoted: 0
  rejected: 0
  weight: 1.0
pyfa.co.id:
  surfaced: 1
  promoted: 0
  rejected: 0
  weight: 1.0
channelstv.com:
  surfaced: 1
  promoted: 0
  rejected: 0
  weight: 1.0
vanguardngr.com:
  surfaced: 1
  promoted: 0
  rejected: 0
  weight: 1.0
premiumtimesng.com:
  surfaced: 1
  promoted: 0
  rejected: 0
  weight: 1.0
thenationonlineng.net:
  surfaced: 1
  promoted: 0
  rejected: 0
  weight: 1.0
pharmanewsonline.com:
  surfaced: 1
  promoted: 0
  rejected: 0
  weight: 1.0
ashp.org:
  surfaced: 2
  promoted: 0
  rejected: 0
  weight: 1.0
pharmexec.com:
  surfaced: 4
  promoted: 0
  rejected: 0
  weight: 1.0
bioxconomy.com:
  surfaced: 1
  promoted: 0
  rejected: 0
  weight: 1.0
dcatvci.org:
  surfaced: 1
  promoted: 0
  rejected: 0
  weight: 1.0
entrytoregulatory.com:
  surfaced: 1
  promoted: 0
  rejected: 0
  weight: 1.0
gilead.com:
  surfaced: 1
  promoted: 0
  rejected: 0
  weight: 1.0
ajmc.com:
  surfaced: 1
  promoted: 0
  rejected: 0
  weight: 1.0
ophthalmologytimes.com:
  surfaced: 1
  promoted: 0
  rejected: 0
  weight: 1.0
investor.elanco.com:
  surfaced: 1
  promoted: 0
  rejected: 0
  weight: 1.0
sec.gov:
  surfaced: 1
  promoted: 0
  rejected: 0
  weight: 1.0
cordenpharma.com:
  surfaced: 1
  promoted: 0
  rejected: 0
  weight: 1.0
contractpharma.com:
  surfaced: 1
  promoted: 0
  rejected: 0
  weight: 1.0
prnewswire.com:
  surfaced: 2
  promoted: 0
  rejected: 0
  weight: 1.0
psrcompliance.com:
  surfaced: 1
  promoted: 0
  rejected: 0
  weight: 1.0
thepharmaletter.com:
  surfaced: 1
  promoted: 0
  rejected: 0
  weight: 1.0
pharmaceuticalcommerce.com:
  surfaced: 1
  promoted: 0
  rejected: 0
  weight: 1.0
einpresswire.com:
  surfaced: 1
  promoted: 0
  rejected: 0
  weight: 1.0
drugdiscoverynews.com:
  surfaced: 1
  promoted: 0
  rejected: 0
  weight: 1.0
theinsurer.com:
  surfaced: 1
  promoted: 0
  rejected: 0
  weight: 1.0
biopharmadive.com:
  surfaced: 1
  promoted: 0
  rejected: 0
  weight: 1.0
medcitynews.com:
  surfaced: 1
  promoted: 0
  rejected: 0
  weight: 1.0
